# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=120)),
                ('book_price', models.CharField(max_length=1500)),
                ('book_img', models.FileField(upload_to='')),
                ('book_pdf', models.FileField(upload_to='')),
                ('book_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_category')),
            ],
        ),
    ]
