# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('book_category_names', models.CharField(max_length=120)),
                ('auther_names', models.CharField(max_length=120)),
                ('book_prices', models.CharField(max_length=1500)),
                ('book_img', models.FileField(upload_to='')),
                ('book_pdf', models.FileField(upload_to='')),
                ('quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
