# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_details_book_category_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_details',
            name='book_img',
        ),
        migrations.RemoveField(
            model_name='cart_details',
            name='book_pdf',
        ),
    ]
