# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_details_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='book_img',
            field=models.CharField(default=0, max_length=1500),
            preserve_default=False,
        ),
    ]
